### ISSUE TITLE
Add basic programs

### ISSUE THREAD

**Issue by Ananthavijay** [Ananthavijay/C-plus-plus-programs#1]

**Comment by Ananthavijay** [comment]
like printing even number series and many more

**Comment by AaronCGoidel** [comment]
@Ananthavijay I think we need to make this repo more organized and also make it clear that we need people to explain their code in comments since this is aimed at people trying to learn how all these concepts work.

**Comment by Ananthavijay** [comment]
@AaronCGoidel yep . I need your help. How can I contact u?

**Comment by Ananthavijay** [comment]
@AaronCGoidel accept the invite ..And make the changes and help me
