### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by Ananthavijay** [Ananthavijay/C-plus-plus-programs#7]

**Comment by cppkyle** [comment]
What do you want it to update to?

**Comment by Ananthavijay** [comment]
Any update on the Read me is accepted

**Comment by Ananthavijay** [comment]
add how to setup turbo c++ or GCC in all the os

**Comment by charubansal12** [comment]
Hi @Ananthavijay The `readme.md` says that the repo contains c++ prorgrams, but the repo name is in conflict with it. Is it done intentionally? It's not much big of an issue though.

**Comment by Ananthavijay** [comment]
No. Without knowing I did it @charubansal12
